name: Build angular workflow

on: 
  push:
    branches: [ main ]
jobs: 
  build-angular-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: setup-node-js
      - uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.x
      - name: install dependences
        run: npm install
      - name: build angular app
        run: npm run build
